name: Deploy website

on: [push]

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: npm ci

      - name: Replace environment.ts
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: false," >> src/environments/environment.ts
          echo "  GIPHY_API_KEY: '${{ secrets.GIPHY_API_KEY }}'," >> src/environments/environment.ts
          echo "  GIPHY_API_VERSION: '${{ secrets.GIPHY_API_VERSION }}'," >> src/environments/environment.ts
          echo "  GIPHY_API_URL: '${{ secrets.GIPHY_API_URL }}'" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          prod_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --dir dist/pi.exchange.fe-coding-challenge/browser \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
            $prod_flag
