name: Deploy website

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: npm ci

      - name: Create environment.development.ts
        run: |
          echo "export const environment = {" >> src/environments/environment.development.ts
          echo "  production: false," >> src/environments/environment.development.ts
          echo "  GIPHY_API_KEY: '${{ secrets.GIPHY_API_KEY }}'," >> src/environments/environment.development.ts
          echo "  GIPHY_API_VERSION: '${{ secrets.GIPHY_API_VERSION }}'," >> src/environments/environment.development.ts
          echo "  GIPHY_API_URL: '${{ secrets.GIPHY_API_URL }}'" >> src/environments/environment.development.ts
          echo "};" >> src/environments/environment.development.ts

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
